### ISSUE TITLE
Why symfony/debug?

### ISSUE THREAD

**Issue by leofeyer** [contao/phpstan#17]
While trying to make the package compatible with Symfony 5, I have noticed that we are using [`symfony/debug`](https://packagist.org/packages/symfony/debug), which has been deprecated and is not available in Symfony 5 anymore. Strange enough, we do not seem to use the package anywhere.

@bytehead Is this a left-over requirement?

**Comment by bytehead** [comment]
Possibly from development.

**Comment by leofeyer** [comment]
I will remove it and see what happens then. 😄
